MODEL:
  TYPE: effnet
  NUM_CLASSES: 1000
  ACTIVATION_FUN: silu
EN:
  STEM_W: 32
  STRIDES: [1, 2, 2, 2, 1, 2, 1]
  DEPTHS: [2, 3, 3, 4, 4, 5, 2]
  WIDTHS: [16, 24, 48, 88, 120, 208, 352]
  EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
  KERNELS: [3, 3, 5, 3, 5, 5, 3]
  HEAD_W: 1408
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 260
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 298
  BATCH_SIZE: 200
NUM_GPUS: 8
OUT_DIR: .
