MODEL:
  TYPE: effnet
  NUM_CLASSES: 1000
  ACTIVATION_FUN: silu
EN:
  STEM_W: 40
  STRIDES: [1, 2, 2, 2, 1, 2, 1]
  DEPTHS: [2, 3, 3, 5, 5, 6, 2]
  WIDTHS: [24, 32, 48, 96, 136, 232, 384]
  EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
  KERNELS: [3, 3, 5, 3, 5, 5, 3]
  HEAD_W: 1536
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 300
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 342
  BATCH_SIZE: 200
NUM_GPUS: 8
OUT_DIR: .
