MODEL:
  TYPE: anynet
  NUM_CLASSES: 10
ANYNET:
  STEM_TYPE: res_stem_cifar
  STEM_W: 16
  BLOCK_TYPE: vanilla_block
  DEPTHS: [9, 9, 9]
  WIDTHS: [16, 32, 64]
  STRIDES: [1, 2, 2]
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 32
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False
OUT_DIR: .
