MODEL:
  TYPE: resnet
  DEPTH: 50
  NUM_CLASSES: 1000
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 4
  STRIDE_1X1: False
  ZERO_INIT_FINAL_TRANSFORM_BN: True
OPTIM:
  BASE_LR: 0.025
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 30, 60, 90]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 64
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 50
NUM_GPUS: 2
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUTPUT_DIR: .
