MODEL:
  TYPE: uninet
  NUM_CLASSES: 10
UNINET:
  BLOCK_TYPE: res_basic_block
  DEPTHS: [1, 9, 9, 9]
  WIDTHS: [16, 16, 32, 64]
  STRIDES: [1, 1, 2, 2]
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  STEP_SIZE: 1
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False
OUTPUT_DIR: .
