MODEL:
  TYPE: effnet
  NUM_CLASSES: 1000
EN:
  STEM_W: 32
  DEPTHS: [1, 2, 2, 3, 3, 4, 1]
  WIDTHS: [16, 24, 40, 80, 112, 192, 320]
  EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
  SE_RATIO: 0.25
  STRIDES: [1, 2, 2, 2, 1, 2, 1]
  KERNELS: [3, 3, 5, 3, 5, 5, 3]
  HEAD_W: 1280
OPTIM:
  BASE_LR: 0.0125
  LR_POLICY: steps
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 32
  IM_SIZE: 224
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 25
  IM_SIZE: 256
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
