MODEL:
  TYPE: regnet
  NUM_CLASSES: 1000
REGNET:
  DEPTH: 23
  W0: 96
  WA: 38.65
  WM: 2.43
  GROUP_W: 40
  BOT_MUL: 1.0
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
  WARMUP_FACTOR: 0.1
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 224
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 100
  IM_SIZE: 256
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
