MODEL:
  TYPE: vgg
  DEPTH: 11
  NUM_CLASSES: 10
VGG:
  NUM_STAGES: 4
  STRIDE2_INDS: [2, 3]
  MAX_POOL_INDS: []
  DS_MULT: 1.0
  WS_MULT: 1.0
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUTPUT_DIR: .
