MODEL:
  TYPE: regnet
  NUM_CLASSES: 1000
REGNET:
  DEPTH: 22
  W0: 24
  WA: 24.48
  WM: 2.54
  GROUP_W: 16
OPTIM:
  LR_POLICY: cos
  BASE_LR: 1.6
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 2048
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 1600
NUM_GPUS: 16
NUM_NODES: 2
OUT_DIR: .
