MODEL:
  TYPE: resnet
  DEPTH: 110
  NUM_CLASSES: 10
RESNET:
  TRANS_FUN: basic_transform
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 32
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False
OUT_DIR: .
